### PR TITLE
Add mention of Rust implementation to Readme

### PR DESCRIPTION
**Pull request by ichorid**
Add mention of Rust-based implementation available at:
https://github.com/Intersubjective/riblt-rust

### CODE REVIEW

**Comment by yangl1996** [comment]
Hi @ichorid , happy to take the PR! But it seems that your repo is private and I cannot access it right now.

**Comment by ichorid** [comment]
hmm... strange

**Comment by ichorid** [comment]
fixed. Somehow, forgot to make it public in the first place :shrug:

(thanks for fast reaction, BTW :wink:)

**Comment by yangl1996** [comment]
Cool! Thanks a lot for porting the lib to Rust---I just took a look and it looks awesome!

**Pull request merged**
